# 7.13 Reshaping and Transposing 

### `reshape` vs. `resize` 
* Method `reshape` returns a _view_ (shallow copy) of the original `array` with new dimensions
* Does _not_ modify the original `array`

In [1]:
import numpy as np

In [2]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [3]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [4]:
grades.reshape(1, 6)

array([[ 87,  96,  70, 100,  87,  90]])

In [5]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

* Method `resize` modifies the original `array`’s shape

In [6]:
grades.resize(1, 6)

In [7]:
grades

array([[ 87,  96,  70, 100,  87,  90]])

### `flatten` vs. `ravel` 
* Can flatten a multi-dimensonal array into a single dimension with methods **`flatten`** and **`ravel`**
* `flatten` _deep copies_ the original array’s data

In [8]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [9]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [10]:
flattened = grades.flatten()

In [11]:
flattened

array([ 87,  96,  70, 100,  87,  90])

In [12]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [13]:
flattened[0] = 100

In [14]:
flattened

array([100,  96,  70, 100,  87,  90])

In [15]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

* Method `ravel` produces a _view_ of the original `array`, which _shares_ the `grades` `array`’s data

In [16]:
raveled = grades.ravel()

In [17]:
raveled

array([ 87,  96,  70, 100,  87,  90])

In [18]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [19]:
raveled[0] = 100

In [20]:
raveled

array([100,  96,  70, 100,  87,  90])

In [21]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

### Transposing Rows and Columns
* Can quickly **transpose** an `array`’s rows and columns
    * “flips” the `array`, so the rows become the columns and the columns become the rows
* **`T` attribute** returns a transposed _view_ (shallow copy) of the `array`

In [22]:
grades.T

array([[100, 100],
       [ 96,  87],
       [ 70,  90]])

In [23]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

### Horizontal and Vertical Stacking
* Can combine arrays by adding more columns or more rows—known as _horizontal stacking_ and _vertical stacking_

In [24]:
grades2 = np.array([[94, 77, 90], [100, 81, 82]])

* Combine `grades` and `grades2` with NumPy’s **`hstack` (horizontal stack) function** by passing a tuple containing the arrays to combine
* The extra parentheses are required because `hstack` expects one argument
* Adds more columns

In [25]:
np.hstack((grades, grades2))

array([[100,  96,  70,  94,  77,  90],
       [100,  87,  90, 100,  81,  82]])

* Combine `grades` and `grades2` with NumPy’s **`vstack` (vertical stack) function**
* Adds more rows

In [26]:
np.vstack((grades, grades2))

array([[100,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [27]:
grades

array([[100,  96,  70],
       [100,  87,  90]])