# 7.4 Filling `array`s with Specific Values
* Functions **`zeros`**, **`ones`** and **`full`** create `array`s containing  `0`s, `1`s or a specified value, respectively

In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

* For a tuple of integers, these functions return a multidimensional `array` with the specified dimensions

In [3]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [5]:
np.full((5, 7), 12)

array([[12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12]])