# 7.9 Universal Functions
* Standalone [**universal functions** (**ufuncs**)](https://docs.scipy.org/doc/numpy/reference/ufuncs.html) perform **element-wise operations** using one or two `array` or array-like arguments (like lists)
* Each returns a **new `array`** containing the results
* Some ufuncs are called when you use `array` operators like `+` and `*`

* Create an `array` and calculate the square root of its values, using the **`sqrt` universal function**

In [2]:
import numpy as np

In [3]:
numbers = np.array([1, 4, 9, 16, 25, 36])

In [4]:
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

* Add two `array`s with the same shape, using the **`add` universal function**
* Equivalent to:
```python
numbers + numbers2
```

In [5]:
numbers2 = np.arange(1, 7) * 10

In [6]:
numbers2

array([10, 20, 30, 40, 50, 60])

In [7]:
np.add(numbers, numbers2)

array([11, 24, 39, 56, 75, 96])

### Broadcasting with Universal Functions
* Universal functions can use broadcasting, just like NumPy `array` operators

In [8]:
np.multiply(numbers2, 5)

array([ 50, 100, 150, 200, 250, 300])

In [9]:
numbers3 = numbers2.reshape(2, 3)

In [10]:
numbers3

array([[10, 20, 30],
       [40, 50, 60]])

In [11]:
numbers4 = np.array([2, 4, 6])

In [12]:
np.multiply(numbers3, numbers4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])

* [Broadcasting rules documentation](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)

### Other Universal Functions

| NumPy universal functions
| ----------
| **_Math_** — `add`, `subtract`, `multiply`, `divide`, `remainder`, `exp`, `log`, `sqrt`, `power`, and more.
| **_Trigonometry_** —`sin`, `cos`, `tan`, `hypot`, `arcsin`, `arccos`, `arctan`, and more.
| **_Bit manipulation_** —`bitwise_and`, `bitwise_or`, `bitwise_xor`, `invert`, `left_shift` and `right_shift`.
| **_Comparison_** —`greater`, `greater_equal`, `less`, `less_equal`, `equal`, `not_equal`, `logical_and`, `logical_or`, `logical_xor`, `logical_not`, `minimum`, `maximum`, and more.
| **_Floating point_** —`floor`, `ceil`, `isinf`, `isnan`, `fabs`, `trunc`, and more.