# 7.10 Indexing and Slicing 
* One-dimensional `array`s can be **indexed** and **sliced** like lists. 

### Indexing with Two-Dimensional `array`s
* To select an element in a two-dimensional `array`, specify a tuple containing the element’s row and column indices in square brackets

In [1]:
import numpy as np

In [2]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])

In [3]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [4]:
grades[0, 1]  # row 0, column 1

96

### Selecting a Subset of a Two-Dimensional `array`’s Rows
* To select a single row, specify only one index in square brackets

In [5]:
grades[1]

array([100,  87,  90])

* Select multiple sequential rows with slice notation

In [6]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

* Select multiple non-sequential rows with a list of row indices

In [7]:
grades[[1, 3]]

array([[100,  87,  90],
       [100,  81,  82]])

### Selecting a Subset of a Two-Dimensional `array`’s Columns
* The **column index** also can be a specific **index**, a **slice** or a **list** 

In [8]:
grades[:, 0]

array([ 87, 100,  94, 100])

In [9]:
grades[:, 1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [10]:
grades[:, [0, 2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])