# 7.11 Views: Shallow Copies
* Views “see” the data in other objects, rather than having their own copies of the data
* Views are shallow copies
*`array` method **`view`** returns a **new** array object with a **view** of the original `array` object’s data

In [1]:
import numpy as np

In [2]:
numbers = np.arange(1, 6)

In [3]:
numbers

array([1, 2, 3, 4, 5])

In [4]:
numbers2 = numbers.view()

In [5]:
numbers2

array([1, 2, 3, 4, 5])

* Use built-in `id` function to see that `numbers` and `numbers2` are **different** objects

In [6]:
id(numbers)

139677626136304

In [7]:
id(numbers2)

139677626136400

* Modifying an element in the original `array`, also modifies the view and vice versa

In [10]:
numbers[1] *= 10

In [11]:
numbers2

array([ 1, 20,  3,  4,  5])

In [12]:
numbers

array([ 1, 20,  3,  4,  5])

In [13]:
numbers2[1] /= 10

In [14]:
numbers

array([1, 2, 3, 4, 5])

In [15]:
numbers2

array([1, 2, 3, 4, 5])

### Slice Views
* Slices also create views

In [16]:
numbers2 = numbers[0:3]

In [17]:
numbers2

array([1, 2, 3])

In [18]:
id(numbers)

139677626136304

In [19]:
id(numbers2)

139677626138128

* Confirm that `numbers2` is a view of only first three `numbers` elements

In [22]:
numbers2[:3]

array([1, 2, 3])

* Modify an element both `array`s share to show both are updated

In [23]:
numbers[1] *= 20

In [24]:
numbers

array([ 1, 40,  3,  4,  5])

In [25]:
numbers2

array([ 1, 40,  3])