# 7.12 Deep Copies
* When sharing **mutable** values, sometimes it’s necessary to create a **deep copy** of the original data
* Especially important in multi-core programming, where separate parts of your program could attempt to modify your data at the same time, possibly corrupting it

* **`array` method `copy`** returns a new array object with an independent copy of the original array's data

In [1]:
import numpy as np

In [2]:
numbers = np.arange(1, 6)

In [3]:
numbers

array([1, 2, 3, 4, 5])

In [4]:
numbers2 = numbers.copy()

In [5]:
numbers2

array([1, 2, 3, 4, 5])

In [6]:
numbers[1] *= 10

In [7]:
numbers

array([ 1, 20,  3,  4,  5])

In [8]:
numbers2

array([1, 2, 3, 4, 5])

### Module `copy`—Shallow vs. Deep Copies for Other Types of Python Objects